# Generated by Django 4.2.5 on 2023-10-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
