# Generated by Django 4.2.5 on 2023-10-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0006_alter_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='image',
            name='for_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sadeem_backend.product'),
        ),
    ]
