# Generated by Django 4.2.5 on 2023-10-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0007_rename_body_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sadeem_backend.product'),
        ),
    ]
