# Generated by Django 4.2.5 on 2023-10-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0009_alter_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
