# Generated by Django 4.2.5 on 2023-10-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0012_alter_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
