# Generated by Django 4.2.5 on 2023-10-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0013_rename_full_name_order_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='arDescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='arTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='enDescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='enTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
