# Generated by Django 4.2.5 on 2023-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0014_remove_product_description_remove_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='arTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='enDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='enTitle',
            field=models.CharField(max_length=100),
        ),
    ]
