# Generated by Django 4.2.5 on 2023-10-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0015_alter_product_ardescription_alter_product_artitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
