# Generated by Django 4.2.5 on 2023-11-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0016_product_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='for_product',
            new_name='forProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='image',
            name='isPrimary',
            field=models.BooleanField(default=False),
        ),
    ]
