# Generated by Django 4.2.5 on 2023-11-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadeem_backend', '0020_alter_imgurtoken_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgurtoken',
            old_name='access_token',
            new_name='accessToken',
        ),
        migrations.RenameField(
            model_name='imgurtoken',
            old_name='refresh_token',
            new_name='refreshToken',
        ),
    ]
